### ISSUE TITLE
Login generate error 500

### ISSUE THREAD

**Issue by mtgred** [mtgred/atlas#14]
username: mtgred
password: password

```
mtgred@mbp (user-component) ~/code/clojure/atlas λ lein repl
nREPL server started on port 50612 on host 127.0.0.1 - nrepl://127.0.0.1:50612
REPL-y 0.3.7, nREPL 0.2.7
Clojure 1.8.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_25-b17
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

atlas.core=> (-main)
Atlas server running on port 2442 with db datomic:mem://temp
#object[clojure.lang.AFunction$1 0x268ee279 "clojure.lang.AFunction$1@268ee279"]
atlas.core=> Mon May 30 16:34:26 CEST 2016 [worker-1] ERROR - POST /login
java.lang.NullPointerException
	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:301)
	at atlas.utils$md5.invokeStatic(utils.clj:8)
	at atlas.utils$md5.invoke(utils.clj:3)
	at atlas.handler$login.invokeStatic(handler.clj:36)
	at atlas.handler$login.invoke(handler.clj:28)
	at atlas.handler$base_handler$fn__4994.invoke(handler.clj:96)
	at bidi.ring$eval1358$fn__1359.invoke(ring.clj:20)
	at bidi.ring$eval1337$fn__1338$G__1328__1347.invoke(ring.clj:12)
	at bidi.ring$make_handler$fn__1367.invoke(ring.clj:37)
	at buddy.auth.middleware$wrap_authentication$fn__4914.invoke(middleware.clj:43)
	at ring.middleware.session$wrap_session$fn__2505.invoke(session.clj:102)
	at ring.middleware.json$wrap_json_body$fn__3352.invoke(json.clj:44)
	at ring.middleware.json$wrap_json_response$fn__3369.invoke(json.clj:87)
	at org.httpkit.server.HttpHandler.run(RingHandler.java:91)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by gaverhae** [comment]
Same behaviour in #11.
